### ISSUE TITLE
Is BucketNotification ONLY support AWS Web Server?

### ISSUE THREAD

**Issue by billschen** [minio/minio-go#801] opened 2017-08-29 03:48 UTC
Today,I want to use [SetBucketNotification](https://docs.minio.io/docs/golang-client-api-reference#SetBucketNotification) to send notification to my server like http://fabide.ltcdex.com/minionotification。
I doubt about the code that use [ARNs](http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)。
and after read code [bucket-notification.go](https://github.com/minio/minio-go/blob/master/bucket-notification.go). I understand only can use arns now.

Is BucketNotification can extend to support coustom url?

**Comment by poornas** [comment] 2017-09-06 01:43
@billschen,have you looked at the bucket notification guide (https://docs.minio.io/docs/minio-bucket-notification-guide#webhooks). If you have configured webhooks on the minio server, you should be able to use SetBucketNotification api call.

**Comment by poornas** [comment] 2017-09-07 19:46
@billschen, were you able to set up bucket notifications? For faster support on general questions, you could join our slack channel at https://slack.minio.io

**Comment by poornas** [comment] 2017-09-11 21:44
@billschen, following up to see if you need further help on this.

**Comment by ebozduman** [comment] 2017-09-18 17:37
Closing this since it is more like a generic question and not a bug.
(Configrued webhooks on the minio server should make it possible to use SetBucketNotification api call.
Reference: https://docs.minio.io/docs/minio-bucket-notification-guide#webhooks )
@billschen : please re-open if you disagree for any reason.

**Closed by ebozduman** 2017-09-18 17:37 UTC
Labels: priority: medium, triage
