### ISSUE TITLE
Amazon S3 is deprecating path-style request URIs

### ISSUE THREAD

**Issue by rmetzler** [minio/minio-go#1102] opened 2019-05-04 12:28 UTC
### AWS S3

AWS is going to change their S3 URI API and stop accepting path-style request on September 30th, 2020. 

https://forums.aws.amazon.com/ann.jspa?annID=6776

>Amazon S3 currently supports two request URI styles in all regions: path-style (also known as V1) that includes bucket name in the path of the URI (example: `//s3.amazonaws.com/<bucketname>/key`), and virtual-hosted style (also known as V2) which uses the bucket name as part of the domain name (example: `//<bucketname>.s3.amazonaws.com/key`). In our effort to continuously improve customer experience, the path-style naming convention is being retired in favor of virtual-hosted style request format. Customers should update their applications to use the virtual-hosted style request format when making S3 API requests before September 30th, 2020 to avoid any service disruptions. Customers using the AWS SDK can upgrade to the most recent version of the SDK to ensure their applications are using the virtual-hosted style request format. 

> Virtual-hosted style requests are supported for all S3 endpoints in all AWS regions. S3 will stop accepting requests made using the path-style request format in all regions starting September 30th, 2020. Any requests using the path-style request format made after this time will fail.

Here is more documentation on how virtual-hosted style S3 URIs are constructed: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

### minio-go

Looking into minio-go, it doesn't seem like `"bucketname.s3.amazonaws.com"` is a valid AmazonEndpoint string in Minio. 

https://github.com/minio/minio-go/blob/master/pkg/s3utils/utils.go#L129-L132

https://github.com/minio/minio-go/blob/master/pkg/s3utils/utils_test.go#L189-L194

**Comment by harshavardhana** [comment] 2019-05-04 17:21
Just use endpoint directly and pass the bucket name we automatically use bucketName as part of the DNS if it's AWS S3

**Comment by kannappanr** [comment] 2019-05-04 17:25
@rmetzler Closing this as working as intended. Please feel free to reach out to us if you have other questions.

**Closed by kannappanr** 2019-05-04 17:25 UTC
Labels: community, priority: medium, working as intended

**Comment by rmetzler** [comment] 2019-05-05 05:29
I probably don't understand the minio-go API as intended.

I'm referring to the fact, that 
```go
s3utils.IsAmazonEndpoint("bucket.s3.amazonaws.com") == false
```

**Comment by harshavardhana** [comment] 2019-05-05 07:37
> ```go
> ```go
> s3utils.IsAmazonEndpoint("bucket.s3.amazonaws.com") == false
> ```
> 
> 
>       
> ```

This is correct behavior @rmetzler we take `bucketname` as part of API operations, not as part of the constructor.
