### ISSUE TITLE
`http: read on closed response body` after loading some time

### ISSUE THREAD

**Issue by oherych** [minio/minio-go#954] opened 2018-03-16 19:04 UTC
Hi, I found some strange bug in my project and cannot find source of problem. My application validate permission and make request to S3 (minio server on local environment) using minio-go. And after some time or count of request  (I not sure) all next request returns error `http: read on closed response body`. I have the same issue on laptop and production server
 
I reprodused it in sandbox project https://github.com/oherych/minio_bug

I'm using version `4.0.9` right now

**Comment by oherych** [comment] 2018-03-19 13:45
I have a lot .... in /debug/pprof/goroutine?debug=2. Looks like goroutine leak
```
goroutine 11795 [select]:
net/http.(*persistConn).writeLoop(0xc42099ed80)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53
```

**Comment by vadmeste** [comment] 2018-03-19 14:08
Thanks @oherych, I followed your steps and was able to reproduce the problem, will keep you updated.

**Comment by vadmeste** [comment] 2018-03-19 15:41
@oherych you can't send a header multiple times.. Once the code starts to send data to ResponseWriter, 200 OK header is implicitly or was explicitly set. So there is no point in calling displayError() when io.Copy() returns an error in your file handler.

```diff
diff --git a/main.go b/main.go
index 5d740e3..8ab91bb 100644
--- a/main.go
+++ b/main.go
@@ -37,8 +37,6 @@ func main() {
 }
 
 func handlerPage(writer http.ResponseWriter, request *http.Request) {
-	writer.WriteHeader(http.StatusOK)
-
 	b, err := os.Open("index.html")
 	if err != nil {
 		displayError(writer, err)
@@ -49,7 +47,7 @@ func handlerPage(writer http.ResponseWriter, request *http.Request) {
 
 	writer.WriteHeader(http.StatusOK)
 	if _, err := io.Copy(writer, b); err != nil {
-		displayError(writer, err)
+		log.Error(err)
 		return
 	}
 }
@@ -74,7 +72,7 @@ func handlerFile(writer http.ResponseWriter, request *http.Request) {
 
 	writer.WriteHeader(http.StatusOK)
 	if _, err := io.Copy(writer, obj); err != nil {
-		displayError(writer, err)
+		log.Error(writer, err)
 		return
 	}
 }
```

**Comment by oherych** [comment] 2018-03-19 17:14
@vadmeste, you right. Style of the project of dirty. But this is just for demo. I removed double headers and BTW thanks for bash script. It is very helpful.

I prepared vide for you https://youtu.be/qC3Mtv95Ma4 . And BTW right now I cannot reproduce this issue without EncryptMaterials keys

**Comment by vadmeste** [comment] 2018-03-19 17:35
@oherych yeah I was also able to reproduce this.. `rsaKey` is actually intended to be used only by one code, it doesn't support parallel use.. so I guess it will be fine if you initialize rsaKey in your file handler and not globally.

**Comment by oherych** [comment] 2018-03-20 10:36
Thanks @vadmeste, looks like fixed. I used `sync.Pool` with keys. But on my opinio it is not clear for another users of this library. Can we protect them?

**Comment by vadmeste** [comment] 2018-03-20 21:01
@oherych actually, client side encryption will be dropped from minio-go and will be replaced by server side encryption.

Closing this as question answered, please free to open again when needed @oherych

**Closed by vadmeste** 2018-03-20 21:01 UTC
Labels: priority: medium

**Comment by harshavardhana** [comment] 2018-03-21 04:46
Client side encryption is already dropped in our 5.0.0 releases.
