### ISSUE TITLE
minio-go api-list.go no longer works with NetApp's S3 Object Storage with version v6.0.14

### ISSUE THREAD

**Issue by basilmusa** [minio/minio-go#1207] opened 2019-12-31 15:05 UTC
The following commit is problematic for NetApp S3 Object Storage:

    https://github.com/minio/minio-go/commit/a42b0e14697ffdcb4ef223384c1cac12738f574f#diff-e038a2d477fad04d158a4afba2faf85e

Please this needs to be reverted back, or else minio-go only works with Amazon S3 and Minio.
For some reason, NetApp S3 is not able to list objects in bucket correctly after this change.

This created problems in the Restic project as discussed here:
https://github.com/restic/restic/issues/2273#issuecomment-527834664

Please this needs to revert back for it to work correctly with NetApp's S3 Object Storage.

**Comment by harshavardhana** [comment] 2019-12-31 18:16
As explained this is not a bug with minio-go but an implementation issue with NetApp object storage server.

**Comment by harshavardhana** [comment] 2019-12-31 19:06
Closing this as implementation issue in NetApp Object Storage Server.

**Closed by harshavardhana** 2019-12-31 19:06 UTC
Labels: wontfix

**Comment by Gorra007** [comment] 2020-03-17 19:09
> 
> 
> Closing this as implementation issue in NetApp Object Storage Server.

"mc" can list the buckets but cannot list the objects inside NetApp. If this is a NetApp issue, why would NetApp work with other S3 clients without any problem then ?

**Comment by harshavardhana** [comment] 2020-03-17 19:13
> "mc" can list the buckets but cannot list the objects inside NetApp. If this is a NetApp issue, why would NetApp work with other S3 clients without any problem then ?

I do not know that @Gorra007 the issue is clearly stated as to why there is a bug in the server implementation, that needs to be addressed.  Bottom line is `mc` works fine with AWS S3 and MinIO without issues.

**Comment by Gorra007** [comment] 2020-03-18 08:18
> 
> 
> > "mc" can list the buckets but cannot list the objects inside NetApp. If this is a NetApp issue, why would NetApp work with other S3 clients without any problem then ?
> 
> I do not know that @Gorra007 the issue is clearly stated as to why there is a bug in the server implementation, that needs to be addressed. Bottom line is `mc` works fine with AWS S3 and MinIO without issues.

I undersdand that `mc` work with AWS S3 and MiniIO without issues. `mc` used to work without issues with NetApp as well before v6.0.14. As NetApp object servers did not got any changes and works fine with other s3 clients , do you still think that there is implementation issue in NetApp server?

**Comment by harshavardhana** [comment] 2020-03-18 18:14
> I undersdand that `mc` works with AWS S3 and MiniIO without issues. `mc` used to work without issues with NetApp as well before v6.0.14. As NetApp object servers did not got any changes and works fine with other s3 clients , do you still think that there is implementation issue in NetApp server?

The implementation issue is with ListObjectsV2 API which is used by default in `mc` @Gorra007  -- I can't claim what API other s3 clients are using. So it is an implementation issue with the NetApp server.

We also found recently other issues with Cleversafe when using `mc` such as they don't support encoding-type=url properly and send unencoded object names - albeit this was easier to fix on the client-side but we cannot do any if ListObjectsV2 doesn't work according to spec @Gorra007

**Comment by Gorra007** [comment] 2020-03-24 09:59
> 
> 
> > I undersdand that `mc` works with AWS S3 and MiniIO without issues. `mc` used to work without issues with NetApp as well before v6.0.14. As NetApp object servers did not got any changes and works fine with other s3 clients , do you still think that there is implementation issue in NetApp server?
> 
> The implementation issue is with ListObjectsV2 API which is used by default in `mc` @Gorra007 -- I can't claim what API other s3 clients are using. So it is an implementation issue with the NetApp server.
> 
> We also found recently other issues with Cleversafe when using `mc` such as they don't support encoding-type=url properly and send unencoded object names - albeit this was easier to fix on the client-side but we cannot do any if ListObjectsV2 doesn't work according to spec @Gorra007

Thanks for the detailed information !

**Comment by dammers** [comment] 2020-11-26 13:44
Did anyone log a case with NetApp support for this issue?
