### ISSUE TITLE
ConditionKeyMap 

### ISSUE THREAD

**Issue by ryanmurf** [minio/minio-go#675] opened 2017-05-09 19:15 UTC
ConditionKeyMap is a Map of set of strings.

```
"Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": false
                }
            }
```

The above condition would fail.

**Comment by ryanmurf** [comment] 2017-05-09 19:16
https://github.com/minio/minio-go/blob/709d63facd42bb185bd5481decc31ad2d521c962/pkg/policy/bucket-policy-condition.go#L22

**Comment by harshavardhana** [comment] 2017-05-09 19:35
@ryanmurf - can you provide instructions on how to reproduce this issue? at the time it was the assumption that each conditions are strings only.

Since looks like new dynamic nature has been added to bucket policy conditions, we have to address this and handle. 

// cc @balamurugana

**Comment by checketts** [comment] 2017-05-09 21:12
I also ran into this bug. I'm using the AWS Java client and in our normal S3 calls we have:


(Client is just the java s3 client)
```java
client.setBucketPolicy(new SetBucketPolicyRequest(bucketName, S3_BUCKET_ENCRYPTION_POLICY.replaceAll("<bucket_name>", bucketName)));
```


The policy is: (note the boolean on the server side encryption line)
```json
{
     "Version": "2012-10-17",
     "Id": "PutObjPolicy",
     "Statement": [
           {
                "Sid": "DenyIncorrectEncryptionHeader",
                "Effect": "Deny",
                "Principal": "*",
                "Action": "s3:PutObject",
                "Resource": "arn:aws:s3:::<bucket_name>/*",
                "Condition": {
                        "StringNotEquals": {
                               "s3:x-amz-server-side-encryption": [
                                       "AES256",
                                       "aws:kms"
                                ]
                         },
                        "Null": {
                               "s3:x-amz-server-side-encryption": true
                        }
                }
           }
     ]
 }
```

**Comment by harshavardhana** [comment] 2017-05-09 22:02
> {
>      "Version": "2012-10-17",
>      "Id": "PutObjPolicy",
>      "Statement": [
>            {
>                 "Sid": "DenyIncorrectEncryptionHeader",
>                 "Effect": "Deny",
>                 "Principal": "*",
>                 "Action": "s3:PutObject",
>                 "Resource": "arn:aws:s3:::<bucket_name>/*",
>                 "Condition": {
>                         "StringNotEquals": {
>                                "s3:x-amz-server-side-encryption": [
>                                        "AES256",
>                                        "aws:kms"
>                                 ]
>                          },
>                         "Null": {
>                                "s3:x-amz-server-side-encryption": true
>                         }
>                 }
>            }
>      ]
>  }

Understood thanks @checketts we will take a look.

**Comment by vadmeste** [comment] 2017-05-16 16:22
http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Conditions_Boolean

According to this document, boolean values have double quotes. But I tested with AWS S3 and it seems it accepts bool without quotes, however when I try to

**Comment by vadmeste** [comment] 2017-05-16 16:23
@ryanmurf, @checketts, can you explain more your exact problem? is there anything that is not working for you?

**Comment by vadmeste** [comment] 2017-05-16 16:40
```
$ aws s3api put-bucket-policy --bucket  vadmeste --policy file://policy.json
$
```

This is a successful operation,  policy.json contains the following json:

```
{
    "Version": "2012-10-17",
    "Id": "123",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::vadmeste/documents/*",
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": false
                }
            }
        }
    ]
}
```

Now, if I want to get the policy:
```
$ aws s3api get-bucket-policy --bucket vadmeste 
{
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"123\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":\"*\",\"Action\":\"s3:*\",\"Resource\":\"arn:aws:s3:::vadmeste/documents/*\",\"Condition\":{\"BoolIfExists\":{\"aws:MultiFactorAuthPresent\":\"false\"}}}]}"
}
```

you can notice that double quote returned by AWS S3

**Comment by vadmeste** [comment] 2017-06-04 21:51
@ryanmurf, @checketts, it looks like AWS S3 supports both boolean with and without quotes, for the moment I don't see how the current state is causing any problem. Could you elaborate why this is a problem for you ?

**Comment by deekoder** [comment] 2017-06-14 20:53
Closing this. Please reopen if you think this is not resolved.

**Closed by deekoder** 2017-06-14 20:53 UTC
Labels: priority: high
