### ISSUE TITLE
CopyObject does not always copy ContentType

### ISSUE THREAD

**Issue by MatSchneider** [minio/minio-go#1133] opened 2019-07-05 18:24 UTC
If you add additional user data to your destination object, CopyObject() will not copy the ContentType of the object but set it to the default value (application/octet-stream).

The following code creates an text object with the ContentType "text/plain". Once it is copied, the ContentType of the copy is "application/octet-stream":

```
package main

import (
	"github.com/minio/minio-go/v6"
	"log"
	"strings"
)
func main() {
	endpoint := "play.min.io:9000"
	accessKeyID := "Q3AM3UQ867SPQQA43P2F"
	secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	useSSL := true

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	if err != nil {
		log.Fatalln(err)
	}

	// Make a new bucket called mymusic.
	bucketName := "cpbucket"
	location := "us-east-1"

	err = minioClient.MakeBucket(bucketName, location)
	if err != nil {
		// Check to see if we already own this bucket (which happens if you run this twice)
		exists, err := minioClient.BucketExists(bucketName)
		if err == nil && exists {
			log.Printf("We already own %s\n", bucketName)
		} else {
			log.Fatalln(err)
		}
	} else {
		log.Printf("Successfully created %s\n", bucketName)
	}

	// lets create an object with test
	opts := minio.PutObjectOptions{
		ContentType:"text/plain",
	}
	input := strings.NewReader("this is a sample object")
	input.Size()
	_, err = minioClient.PutObject(bucketName,
			"original", input, input.Size(), opts)
	if err != nil {
		log.Println(err)
	}

	src := minio.NewSourceInfo(bucketName, "original", nil)
	//src.Headers.Add("Content-Type", "text/plain") <- this is a workaround
	dst, err := minio.NewDestinationInfo("test",
					     "copyObj",
					     nil,
					     map[string]string{
					        "hello": "myheader",
					     })
	if err != nil {
		log.Println(err)
		return
	}
	if err := minioClient.CopyObject(dst, src); err != nil {
		log.Println(err)
		return
	}
	result, _ := minioClient.StatObject("test", "copyObj", minio.StatObjectOptions{})
	log.Printf("content type: %s\n", result.ContentType)
}
``` 

If you replace ` map[string]string{"hello": "myheader",})` by `nil` the copy works as expected.

**Comment by kannappanr** [comment] 2019-07-06 23:42
@MatSchneider This is working as expected. PTAL https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

It says 
```
When copying an object, you can preserve most of the metadata (default) or specify new metadata. However, the ACL is not preserved and is set to private for the user making the request.
```

So, if you specify metadata, the existing ones will be overwritten.

**Comment by harshavardhana** [comment] 2019-07-08 03:15
minio-go always replaces the destination object metadata in current implementation. We can see if we can preserve the metadata when no metadata is set. @kannappanr

**Comment by sinhaashish** [comment] 2019-07-09 06:53
IMO this is working as intended .
There are two cases 
 **Case 1** : When no meta data is passed to the destination object . In this case  value `x-amz-metadata-directive` is `COPY` which is the default value. @MatSchneider  This is the case when you pass nil as the meta data in the destination object.
`minio-go` code  https://github.com/minio/minio-go/blob/6898080dc99f7dbd177749e1baa4d2b8f0569ca6/api-compose-object.go#L96

			
**Case 2:**  :When you pass metadata to destination object . In this case  value `x-amz-metadata-directive` is `REPLACE`. Passing the  metadata in destination  is actually replacing the metadata if already present so `x-amz-metadata-directive` is   set to `REPLACE`.			

[Refer ](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html
)			
``` 
x-amz-metadata-directive: Specifies whether the metadata is copied from the source object or is replaced with metadata provided in the request.

1. If the metadata is copied, all of the metadata except for the version ID remains unchanged. In addition, the server-side-encryption, storage-class and website-redirect-location metadata from the source is not copied. If you specify this metadata explicitly in the copy request, Amazon S3 adds this metadata to the resulting object. If you specify headers in the request that specifies user-defined metadata, Amazon S3 ignores these headers.

2. If the metadata is replaced, all of the original metadata is replaced by the metadata that you specify.

Type: String

Default: COPY

Valid values: COPY | REPLACE

Constraints: Values other than COPY or REPLACE result in an immediate 400-based error response. You can't copy an object to itself unless you specify the MetadataDirective header and set its value to REPLACE.

```

**Comment by MatSchneider** [comment] 2019-07-09 09:02
Thanks for the detailed explanation including the documentation references. 

From my "higher layer SDK user"-perspective, the behaviour seems unexpected. Replacing meta information by setting `userMeta` is something I can understand. But the "ContenType" feels like something different (means: not like `userMeta`) the way the Minio SDK is designed.

**Comment by harshavardhana** [comment] 2019-07-09 15:18
@MatSchneider contentType is user metadata AWS S3 doesn't differentiate we cannot selectively choose what to copy and what to replace. Its either full copy or full replace in accordance with the API.

So the code is working as intended.

**Comment by harshavardhana** [comment] 2019-07-09 15:18
Will close this as working as intended.

**Closed by harshavardhana** 2019-07-09 15:18 UTC
Labels: community, priority: medium
