### ISSUE TITLE
GetObject not returning error for non-existent file

### ISSUE THREAD

**Issue by sb10** [minio/minio-go#654] opened 2017-04-18 10:51 UTC
I'm using minio-go to access files in a Ceph Object Gateway with an S3 frontend. It seems to work perfectly for all read, write and listing operations I've tried, except for this behaviour:

```
package main

import (
	"bufio"
	"fmt"
	"github.com/minio/minio-go"
	"io"
	"log"
	"os"
)

func main() {
	bucket := "sb10"
	remotePath := "non-existent.file"
	localPath := "/tmp/non-existent.file"

	s3Client, err := minio.New(os.Getenv("AWS_S3_ENDPOINT"), os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), true)
	if err != nil {
		log.Fatalln(err)
	}

	err = s3Client.FGetObject(bucket, remotePath, localPath)
	fmt.Printf("FGetObject err = %s\n", err)

	object, err := s3Client.GetObject(bucket, remotePath)
	fmt.Printf("GetObject err = %s\n", err)
	if err == nil {
		err = Stream(object)
		fmt.Printf("Stream err = %s\n", err)
	}
}

func Stream(r io.Reader) error {
	br := bufio.NewReader(r)
	b := make([]byte, 10000, 10000)
	for {
		_, err := br.Read(b)
		if err != nil {
			if err == io.EOF {
				break
			}
			fmt.Println("Stream will return a non-EOF error")
			return err
		}
	}
	return nil
}
```

Running this code (where $AWS_S3_ENDPOINT == cog.mydomain.tld) gives this output:

```
FGetObject err = The specified key does not exist.
GetObject err = %!s(<nil>)
Stream will return a non-EOF error
Stream err =
```

I understand that GetObject should return the same error as FGetObject did, but it doesn't? Any thoughts as to what I'm doing wrong, or how I can know the object didn't exist without doing an additional call (like StatObject)?

**Comment by vadmeste** [comment] 2017-04-18 10:57
@sb10, I tested your code, I've only changed the bucket name, this is my output:

$ go run main.go 
FGetObject err = The specified key does not exist.
GetObject err = %!s(<nil>)
Stream will return a non-EOF error
Stream err = The specified key does not exist.

**Comment by vadmeste** [comment] 2017-04-18 10:57
@sb10, are you using the last minio-go version ?

**Comment by sb10** [comment] 2017-04-18 11:02
```
$ go get -v -u github.com/minio/minio-go
github.com/minio/minio-go (download)

$ cd $GOPATH/src/github.com/minio/minio-go
$ git status
# On branch master
nothing to commit (working directory clean)

$ git log | head -n 3
commit 6b96fedaae1177cb670c5bc70fb438446cd96d9c
Author: David Collier-Brown <davecb@spamcop.net>
Date:   Mon Apr 17 16:30:34 2017 -0400
```

**Comment by vadmeste** [comment] 2017-04-18 11:08
Weird, is this systematic for you? I tried many times. Also can you create a new bucket and test again?

**Comment by sb10** [comment] 2017-04-18 11:12
Yes, it happens 100% of the time.

My output if I change bucket to a non-existant bucket:

```
FGetObject err =
GetObject err = %!s(<nil>)
Stream will return a non-EOF error
Stream err =
```
(I'd have expected the log.Fatalln to trigger?)

My output if I change bucket to a brand new bucket I created with `s3cmd mb s3://sb102`:

```
FGetObject err = The specified key does not exist.
GetObject err = %!s(<nil>)
Stream will return a non-EOF error
Stream err =
```
(same as before)

**Comment by sb10** [comment] 2017-04-18 11:16
What's your go version?

```
$ go version
go version go1.8 linux/amd64
```

I see that 1.8.1 came out and can upgrade if you think that might be the issue. Or could it be any other dependency I need to update?

**Comment by vadmeste** [comment] 2017-04-18 11:22
I am testing with go1.7.5.

Can you add this line to your code, just after minio.New() ?

   `s3Client.TraceOn(nil)`

This will help us debug better.

**Comment by sb10** [comment] 2017-04-18 11:26
New output with TraceOn (manually redacting my domain):

```
---------START-HTTP---------
GET /sb10/?location= HTTP/1.1
Host: cog.redacted
User-Agent: Minio (linux; amd64) minio-go/2.0.4
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170418/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170418T112333Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 127
Date: Tue, 18 Apr 2017 11:23:33 GMT
X-Amz-Request-Id: tx000000000000001a95356-0058f5f735-7e8203-default
---------END-HTTP---------
---------START-HTTP---------
HEAD /sb10/non-existent.file HTTP/1.1
Host: cog.redacted
User-Agent: Minio (linux; amd64) minio-go/2.0.4
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170418/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170418T112333Z

HTTP/1.1 404 Not Found
Content-Length: 215
Accept-Ranges: bytes
Content-Type: application/xml
Date: Tue, 18 Apr 2017 11:23:33 GMT
X-Amz-Request-Id: tx000000000000001a95357-0058f5f735-7e8203-default
---------END-HTTP---------
FGetObject err = The specified key does not exist.
GetObject err = %!s(<nil>)
---------START-HTTP---------
GET /sb10/non-existent.file HTTP/1.1
Host: cog.redacted
User-Agent: Minio (linux; amd64) minio-go/2.0.4
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20170418/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170418T112333Z
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Content-Length: 215
Accept-Ranges: bytes
Content-Type: application/xml
Date: Tue, 18 Apr 2017 11:23:33 GMT
X-Amz-Request-Id: tx000000000000001a95358-0058f5f735-7e8203-default

<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>sb10</BucketName><RequestId>tx000000000000001a95358-0058f5f735-7e8203-default</RequestId><HostId>7e8203-default-default</HostId></Error>---------END-HTTP---------
Stream will return a non-EOF error
Stream err =
```

**Comment by vadmeste** [comment] 2017-04-18 11:39
@sb10, Ceph is not returning the error message as S3 does, that's why you are seeing a blank error.

`<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>sb10</BucketName><RequestId>tx000000000000001a95358-0058f5f735-7e8203-default</RequestId><HostId>7e8203-default-default</HostId></Error>`

**Comment by vadmeste** [comment] 2017-04-18 11:41
@sb10, you can use minio-go ToErrorResponse() API and test directly on Code field:

like: 
```
if ToErrorResponse(err).Code == "NoSuchKey" {
   fmt.Println("Object not found")
}
```

But also Ceph needs to return a message to follow S3 spec as much as possible.

**Comment by sb10** [comment] 2017-04-18 12:08
Great, thanks. I'll use ToErrorResponse and let my cog admin know about this. I'll leave it up to you if you want to close this issue right now or work on special-caseing minio-go to not return blank when a <Code> is defined in the error.

**Comment by jrandall** [comment] 2017-04-18 22:30
I agree it would be better if Ceph included a `Message` but I also think minio-go should do something reasonable if it is missing. An S3 error response should be interpretable without a `Message` based only on the value of `Code`. If there were an S3 specification, it would be reasonable for `Code` to be required but `Message` be optional (to provide more information about the specific error). `minio-go` should not require `Message` in order to sensibly process the error. This was also the underlying problem behind https://github.com/minio/minio-go/issues/629 which we fixed in minio-go. 

It would seem reasonable in this case to handle a missing `Message` by either falling back to an internal string corresponding to the `Code` or even just the `Code` string itself.

**Comment by harshavardhana** [comment] 2017-04-19 03:34
The problem is we can't keep adding things like this for lack of implementation issues on S3 compatible storage implementations. 

S3 provides a proper Error XML spec http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html here. It should be followed. 

@jrandall We added a fix in #629 is a different scenario altogether where Code is sufficient and checking of Message was superfluous. 

But in this scenario a client shouldn't be constructing a message on its own, minio-go as a library shouldn't carry verbatim strings which can possibly change in the future where we will have inconsistent strings.  

A Message string here is also as much part of S3 spec as the Code field.  This should be considered as Ceph bug and fixed properly on the server side.

**Comment by jrandall** [comment] 2017-04-20 22:49
As I said, I agree that it is a bug in Ceph's radosgw that it doesn't always include an error message, and there is an issue on their tracker (http://tracker.ceph.com/issues/18343) and a PR (https://github.com/ceph/ceph/pull/12485) for this. The PR had stalled, but we are attempting to get it moving again and will hopefully get this fixed at that end. However, it would still be nice if minio-go could handle the situation slightly better. 

Respectfully, I don't agree in general that "in this scenario a client shouldn't be constructing a message on its own" - Amazon ErrorResponses documentation you referenced anticipates that some clients would do exactly that:
```
The error message contains a generic description of the error condition in English. It is intended for a human audience. Simple programs display the message directly to the end user if they encounter an error condition they don't know how or don't care to handle. Sophisticated programs with more exhaustive error handling and proper internationalization are more likely to ignore the error message.
```

The Amazon documentation suggests to me that some clients might choose to use the value of `Code` as a key to generate an error message in an appropriate language and/or perhaps specific to the context in which it was triggered (i.e. including some potentially relevant details of the request). 

It would be consistent with Amazon's documentation for minio-go to ignore all `Message` strings and just generate its own error messages based only on `Code` values - clients should in any case not be parsing the `Message` strings, only using them to display to the user. I'm not suggesting that minio-go should actually do that, only that we change the way that `Error()` stringifies the error response such that it is interpretable in the event that `Message` happens to be empty or if the message doesn't make sense without also knowing the code. 

I don't really understand the reluctance - clients of minio-go should really only be using the stringification of the ErrorResponse to log or display the error to the user, and I don't see avoiding returning an empty string for a non-nil error is going to be anything but an improvement. 

One way to handle this might just be to always mention the `Code` in the ErrorRespnse Error() string:
```
func (e ErrorResponse) Error() string {
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}
```

The issue there is that given the typical Amazon codes and messages, you'd wind up with redundant strings like: 
`AccessDenied: Access Denied`
or
`NoSuchKey: The specified key does not exist.`

That is why I would propose something like this:
```
func (e ErrorResponse) Error() string {
	message := e.Message
	if message == "" {
		message = "ErrorResponse Code " + e.Code
	}
	return message
}
```

**Comment by deekoder** [comment] 2017-04-20 23:29
i will reopen this for now so that we can discuss this further.

**Comment by harshavardhana** [comment] 2017-04-21 00:28
> I don't really understand the reluctance - clients of minio-go should really only be using the stringification of the ErrorResponse to log or display the error to the user, and I don't see avoiding returning an empty string for a non-nil error is going to be anything but an improvement.

There is no reluctance we would do it if it generally the right thing and helps a user. But in this scenario i deliberately argued to expose a situation where we shouldn't compromise. 

> Respectfully, I don't agree in general that "in this scenario a client shouldn't be constructing a message on its own" - Amazon ErrorResponses documentation you referenced anticipates that some clients would do exactly that:

The message indicates that client can decide what to choose, but it doesn't validate that Message itself is optional.  But i get your point we can add verbatim strings for some common errors and rest we can fall back to Code.  

FWIW here is a PR to handle this https://github.com/minio/minio-go/pull/655

**Closed** 2017-04-21 14:33 UTC
Labels: community, priority: medium

**Comment by arunpal-kiwi** [comment] 2017-10-28 07:59
Hi i am using minio 3.0.6 . its working fine for upload file in java .But it give me a error while i am trying to download a file

error occured
ErrorResponse(code=NoSuchKey, message=The specified key does not exist., bucketName=null, objectName=null, resource=/resourse-server/284/health/1509086845373.doc, requestId=3L137, hostId=3L137)
request={method=GET, url=http://54.85.114.48:9000/resourse-server/284/health/1509086845373.doc, headers=Range: bytes=0-
Host: 54.85.114.48:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20171028T063134Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171028/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=404, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-07-24T18-27-35Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F1A834C5D82B02
Date: Sat, 28 Oct 2017 06:31:34 GMT
Transfer-Encoding: chunked
}
please help me

**Comment by thaney071** [comment] 2019-04-11 22:47
At the very least the documentation for the minio-go client should be updated to show the usage of ToErrorResponse() for checking. This is not intuitive or well documented otherwise.

**Comment by thaney071** [comment] 2019-04-11 23:09
The bigger problem I am having here is that the err is not even set when calling GetObject() for an invalid object. there is no error until you try to read from the object, which means now I have to hope the error string doesn't change since I need to be able to return back if it was a general read error or if the object just doesn't exist. 

In general, we have a call for BucketExists, but not for ObjectExists. The later is also needed.

**Comment by kannappanr** [comment] 2019-04-12 00:49
@thaney071 You can look at this example

```
package main

import (
	"io"
	"log"
	"os"

	"github.com/minio/minio-go"
)

func main() {

	s3Client, err := minio.NewWithRegion("play.min.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true, "us-east-1")
	if err != nil {
		log.Fatalln(err)
	}
	s3Client.TraceOn(os.Stderr)
	reader, err := s3Client.GetObject("test", "non-existent-bucket", minio.GetObjectOptions{})
	if err != nil {
		log.Fatalln(err)
	}
	defer reader.Close()

	stat, err := reader.Stat()
	if err != nil {
		log.Fatalln("reader.Stat threw an error:", err)
	}

	localFile, err := os.Create("my-testfile")
	if err != nil {
		log.Fatalln(err)
	}
	defer localFile.Close()

	if _, err := io.CopyN(localFile, reader, stat.Size); err != nil {
		log.Fatalln(err)
	}
}
```
You can also use https://docs.min.io/docs/golang-client-api-reference.html#StatObject
