### ISSUE TITLE
I can't update the new sdk of minio-go

### ISSUE THREAD

**Issue by yingyan003** [minio/minio-go#902] opened 2017-12-23 12:44 UTC
When I use command "go get -u github.com/minio/minio-go" to update an existing sdk ,it return an error "package github.com/minio/minio-go: directory "/myproject/src/github.com/minio/minio-go" is not using a known version control system".How do I do whithout deleting and re-downloading it?Thanks for reading my question.

**Comment by harshavardhana** [comment] 2017-12-23 13:17
looks like you have downloaded minio-go without any `git` version control system. You could potentially 
```
rm -rf  "/myproject/src/github.com/minio/minio-go"
```

and then 

```
go get -u github.com/minio/minio-go
```

**Comment by kannappanr** [comment] 2017-12-24 07:01
@yingyan003 Closing this issue as working as intended. Please feel free to re-open the issue, if the suggestion does not work.

**Closed by kannappanr** 2017-12-24 07:01 UTC
