### ISSUE TITLE
Endless waiting in ListObjects() with doneCh

### ISSUE THREAD

**Issue by runningmaster** [minio/minio-go#386] opened 2016-04-22 10:46 UTC
I did some simple test for ListObjects() and got endless waiting when I attempt send value into doneCh. Note: backet contains more then 14 objects (15).
```
func testListBackets() {
	doneCh := make(chan struct{})
	defer close(doneCh)

	n := 0
	objectCh := s3cli.ListObjects("backet", "", true, doneCh)
	for object := range objectCh {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		n++
		fmt.Println(n, object)
		if n == 14 {
			doneCh <- struct{}{}
		}
		// waiting here ........................................................
		fmt.Println(n) // Println does not print 14
	}
}
```

**Comment by vadmeste** [comment] 2016-04-22 10:58
@runningmaster: you must have a directory between your objects..
ping @krishnasrinivas

**Comment by krishnasrinivas** [comment] 2016-04-22 13:13
what would be happening is the ListObjects goroutine in minio-go would have returned after sending the last object (15th object) in  the objectCh and there would be no one doing `<- doneCh` causing this loop to block when it does `doneCh <-`

@runningmaster you can confirm this by changing this to:
```
        if n == 13 {
            doneCh <- struct{}{}
        }
```
and confirm that this does not block, and that it only blocks when you do n == 14 (when there are 15 objects)

**Comment by runningmaster** [comment] 2016-04-22 16:51
@vadmeste 

> you must have a directory between your objects

With `recursive == false` my example works similar (with waiting)

```
objectCh := s3cli.ListObjects("backet", "", false, doneCh)
```

**Comment by runningmaster** [comment] 2016-04-22 17:18
@krishnasrinivas 

> you can confirm this by changing this to

In any case when n <= len(objects) I get block.

**Comment by harshavardhana** [comment] 2016-04-22 17:23
```
func testListBackets() {
    doneCh := make(chan struct{})

    objectCh := s3cli.ListObjects("backet", "", true, doneCh)
    n := 0
    for object := range objectCh {
        if object.Err != nil {
            fmt.Println(object.Err)
            return
        }
        n += len(objects)
        if n == 14 {
            doneCh <- struct{}{}
        }
   }
   fmt.Println(n)
}
```

**Comment by vadmeste** [comment] 2016-04-22 17:24
> // waiting here ........................................................
>  fmt.Println(n) // Println does not print 14

First, no reason for your code to wait there, you have to check again where exactly it is blocking, personally, I think it doesn't and it simply quits  testListBackets() function.

Otherwise, would you mind if you paste the content of your directory using mc command?
( mc ls and mc ls -r)

**Comment by harshavardhana** [comment] 2016-04-22 17:29
The problem is what @krishnasrinivas - mentioned, the doneCh blocks because go-routine has died/returned already for the last object.  What it needs to do is not die and return on the last object, but wait for explicit 'close(doneCh)'  or 'doneCh <- struct{}{}'

**Comment by runningmaster** [comment] 2016-04-22 17:40
My goal is to get the specified number of objects.
Something similar to ListObectsN("backet", "", true, n)

**Comment by harshavardhana** [comment] 2016-04-22 18:39
> My goal is to get the specified number of objects.
> Something similar to ListObectsN("backet", "", true, n) or SELECT TOP N in SQL :)

I don't see anything blocking at all both with more objects and less objects, the problem you might be seeing is that the objectCh is not a singleton channel it is a buffered channel of 1000 entries. 

So up to 1000 it will always return on the first batch.  Now you can filter them out easily but you have to read upto n < 15 

```
// +build ignore

package main

import "fmt"
import "github.com/minio/minio-go"
import "os"

func main() {
	s3Client, err := minio.New(os.Getenv("S3_ENDPOINT"), os.Getenv("ACCESS_KEY"), os.Getenv("SECRET_KEY"), false)
	if err != nil {
		fmt.Println(err)
		return
	}
	doneCh := make(chan struct{})

	n := 0
	objectCh := s3Client.ListObjects("miniocloud", "", true, doneCh)
	for n < 15 {
		object := <-objectCh
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		n++
		fmt.Println(n, object)
	}
	close(doneCh)
}
```

Verifying your code with just 15 objects in a bucket, see if there is a race.

**Comment by harshavardhana** [comment] 2016-04-22 19:01
Ah found the problem the issue is done channel itself. 

Your code hangs but that is because it's not a buffered channel - this is common behavior. For example 

This will hang. 
```
func testListBackets() {
    doneCh := make(chan struct{})
    defer close(doneCh)

    n := 0
    objectCh := s3cli.ListObjects("backet", "", true, doneCh)
    for object := range objectCh {
        if object.Err != nil {
            fmt.Println(object.Err)
            return
        }
        n++
        fmt.Println(n, object)
        if n == 14 {
            doneCh <- struct{}{}
        }
        // waiting here ........................................................
        fmt.Println(n) // Println does not print 14
    }
}
``` 

To fix this using an unbuffered channel.
```
func testListBackets() {
    doneCh := make(chan struct{})

    n := 0
    objectCh := s3cli.ListObjects("backet", "", true, doneCh)
    for object := range objectCh {
        if object.Err != nil {
            fmt.Println(object.Err)
            return
        }
        n++
        fmt.Println(n, object)
        if n == 14 {
            close(doneCh)
        }
        // waiting here ........................................................
        fmt.Println(n) // Println does not print 14
    }
}
```

To use ``doneCh <- struct{}{}`` we need a buffered channel. 

```
func testListBackets() {
    doneCh := make(chan struct{}, 1)
    defer close(doneCh)

    n := 0
    objectCh := s3cli.ListObjects("backet", "", true, doneCh)
    for object := range objectCh {
        if object.Err != nil {
            fmt.Println(object.Err)
            return
        }
        n++
        fmt.Println(n, object)
        if n == 14 {
            doneCh <- struct{}{}
        }
        // waiting here ........................................................
        fmt.Println(n) // Println does not print 14
    }
}
```

**Comment by harshavardhana** [comment] 2016-04-22 19:03
Along with this we need to change internally to not use a 1000 entry buffered channel, so that doneCh is honored properly. Otherwise the loop would continue since there are enough entries still to be read from the channel. 

We will document the different behaviors of doneCh in an example. Thanks for the heads up @runningmaster

**Comment by krishnasrinivas** [comment] 2016-04-22 19:22
actually, we have `objectStatCh := make(chan ObjectInfo, 1000)` which is the reason you are seeing this behavior.
We will get back on this.

**Comment by harshavardhana** [comment] 2016-04-22 19:23
```

// List 'N' number of objects from a bucket-name with a matching prefix.
func listObjectsN(bucket, prefix string, recursive bool, N int) (objsInfo []ObjectInfo, err error) {
        // Create a done channel to control 'ListObjects' go routine.
        doneCh := make(chan struct{}, 1)

        // Free the channel upon return.
        defer close(doneCh)

        i := 0
        for object := range s3Client.ListObjects(bucket, prefix, recursive, doneCh) {
                if object.Err != nil {
                        return nil, object.Err
                }
                i++
                objsInfo = append(objsInfo, object)
                // Verify if we have printed N objects.
                if i == N {
                        // Indicate ListObjects go-routine to exit and stop
                        // feeding the objectInfo channel.
                        doneCh <- struct{}{}
                }
        }
        return objsInfo, nil
}

func main() {
        // Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-bucketname and my-prefixname
        // are dummy values, please replace them with original values.

        // Requests are always secure (HTTPS) by default. Set insecure=true to enable insecure (HTTP) access.
        // This boolean value is the last argument for New().

        // New returns an Amazon S3 compatible client object. API copatibality (v2 or v4) is automatically
        // determined based on the Endpoint value.
        s3Client, err := minio.New("s3.amazonaws.com", "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", false)
        if err != nil {
                fmt.Println(err)
                return
        }

        // List recursively first 100 entries for prefix 'my-prefixname'.
        recursive := true
        objsInfo, err := listObjectsN("my-bucketname", "my-prefixname", recursive, 100)
        if err != nil {
                fmt.Println(err)
        }

        // Print all the entries.
        fmt.Println(objsInfo)
}
``

**Comment by harshavardhana** [comment] 2016-04-22 19:25
This is the complete example on how it can be achieved after the patch #387 is merged.

**Closed** 2016-04-22 20:18 UTC
Labels: bug, enhancement, in-progress
