### ISSUE TITLE
functional test fails for testGetObjectClosedTwiceV2 against s3 gateway

### ISSUE THREAD

**Issue by poornas** [minio/minio-go#826] opened 2017-09-26 02:10 UTC
Needs investigation.
```time="2017-09-25T23:58:06Z" level=fatal msg="Error:We encountered an internal error, please try again.minio-go-testn40d4u2mefm3tmfct0id10whbpoovz36qiesiravhvj2ftf" file=functional_tests.go function:=main.testGetObjectClosedTwiceV2 line#=2568```

Mint image built from  commit 158108152fc86c52d5543995e0e7634bf1b6da74
Minio version:
Version: 2017-09-25T21:57:17Z
Release-Tag: RELEASE.2017-09-25T21-57-17Z
Commit-ID: d3eb5815d9951fdb82d0134b7651368bab71d72e

**Comment by harshavardhana** [comment] 2017-09-26 05:09
Which version of mint, minio-go version is this for? - Github bug can be more descriptive here..

**Comment by poornas** [comment] 2017-09-26 05:18
done.

**Comment by balamurugana** [comment] 2017-09-26 22:32
Unable to reproduce this in latest HEAD of minio and minio-go.

**Comment by deekoder** [comment] 2017-09-27 17:32
can it be closed @poornas  @balamurugana

**Comment by poornas** [comment] 2017-09-27 18:01
ran minio-go SDK again from release version of minio-go and latest minio master - just see the size mismatch error which is being fixed. We could close this issue and reopen if encountered again. 
```
time="2017-09-26T20:06:14Z" level=fatal msg="Error: number of bytes does not match, want 106368, got 33792\n" file=functional_tests.go function:=main.testGetObjectClosedTwiceV2 line#=2572
```

**Comment by balamurugana** [comment] 2017-09-27 19:03
As minio-go HEAD is working fine, this bug is `FIXED UPSTREAM`

**Comment by deekoder** [comment] 2017-09-29 19:27
Nothing to fix in minio-go. Invalid/Won't Fix resolution.

**Closed by deekoder** 2017-09-29 19:27 UTC
Labels: priority: medium, wontfix
