### ISSUE TITLE
Why is minio using so much memory?

### ISSUE THREAD

**Issue by y0ssar1an** [minio/minio-go#1081] opened 2019-02-27 06:34 UTC
We are using `minio-go` to concurrently upload files to S3. It's using an excessive amount of memory and I'm trying to understand why.
```
3155904.50MB 55.52% 55.52% 3156280.75MB 55.53%  github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength
```
This is from a pprof allocs profile (`/debug/pprof/allocs`).

Is there anything we can do to reduce `minio-go`'s memory usage? Are we misusing the package?
Sorry, that I can't post code extracts, because this is a closed source repo.

**Comment by harshavardhana** [comment] 2019-02-27 07:55
Yes make sure to provide the actual file size of the object that you are trying to upload. Memory utilization is higher if you don't specify the content length in your PutObject call.

**Comment by nitisht** [comment] 2019-02-28 09:48
closing this as working as intended @y0ssar1an . Do feel free to reopen if it still takes lot of memory after specifying the content length

**Closed by nitisht** 2019-02-28 09:48 UTC
Labels: community, priority: medium, working as intended

**Comment by y0ssar1an** [comment] 2019-02-28 16:07
Thank you for the advice! I changed the code to pass the content length wherever possible, and the memory usage came way down.
