### ISSUE TITLE
File corruption on S3 upload

### ISSUE THREAD

**Issue by falzm** [minio/minio-go#1124] opened 2019-06-19 15:05 UTC
Hi,

I'm working for Exoscale, a cloud company the offers an S3-compatible Object Storage service named SOS. We've noticed that [content corruption occurs](https://github.com/exoscale/cli/issues/137) when uploading large files on SOS with the `minio-go` package, which doesn't happen with the same file on the same service endpoint using [s3cmd](https://github.com/s3tools/s3cmd):

```console
$ md5sum largefile
e3fcf94aad137e4d8da9ef04c5647d57  largefile

$ s3cmd put largefile s3://marc-templates/largefile-s3cmd
upload: 'largefile' -> 's3://marc-templates/largefile-s3cmd'  [part 1 of 83, 15MB] [1 of 1]
 15728640 of 15728640   100% in    2s     7.22 MB/s  done
...
upload: 'largefile' -> 's3://marc-templates/largefile-s3cmd'  [part 83 of 83, 14MB] [1 of 1]
 14811296 of 14811296   100% in    1s     7.09 MB/s  done

$ exo sos upload -p largefile-exo marc-templates largefile
done! 100 % [==============================================================] largefile

$ s3cmd ls --list-md5 s3://marc-templates/
2019-06-19 14:52 1304559776   ca211e79fdd8c34a1231093eaa0dfa78-20  s3://marc-templates/largefile-exo
2019-06-19 14:41 1304559776   e3fcf94aad137e4d8da9ef04c5647d57  s3://marc-templates/largefile-s3cmd
```

It is possible that we may have messed up in our CLI implementation (available [here](https://github.com/exoscale/cli/blob/master/cmd/sos_upload.go)), but it may also be a bug in this package. Note that we don't see this issue with smaller files.

Could you please have a look?

**Comment by harshavardhana** [comment] 2019-06-19 16:12
There is no corruption issue here @falzm minio-go uploads in single PUT upto 128MiB whereas s3cmd uses multipart upload very early.

It is incorrect to rely on md5sum to validate the content uploaded, since they are not guaranteed to be md5sum of the actual object.

You should download the file and pipe it to md5sum to see the real value.

**Comment by harshavardhana** [comment] 2019-06-19 16:18
Btw you should also depend on the v6 path 

https://github.com/exoscale/cli/blob/master/go.mod#L21

Should be `github.com/minio/minio-go/v6` and use the latest.

**Comment by harshavardhana** [comment] 2019-06-19 16:21
Also you may want to read the documentation

https://godoc.org/github.com/minio/minio-go#Client.PutObject
https://godoc.org/github.com/minio/minio-go#PutObjectOptions

**Comment by kannappanr** [comment] 2019-06-20 05:02
@falzm Closing the issue as answered. Please feel free to re-open if you feel otherwise

**Comment by brutasse** [comment] 2019-06-20 08:17
Hi @harshavardhana, thanks for the answers! What's confusing here is that s3cmd *does* use multipart, but also uploads the md5 as object metadata, for `--list-md5` to still work with multipart-uploaded objects. The underlying `ETag` for the s3cmd upload is a multipart-style one.

You mentioned that the `ETag` is computed differently depending on the use of multipart or not, but uploading the same object twice in multipart with the same part size must result in the same `ETag`: in multipart, the `ETag` is the md5 of all the part md5's, suffixed with the number of parts. If 2 uploads for the same obj and part size don't have the same `ETag`, at least one of them is wrong.

What we are observing here is that a multipart upload with `s3cmd` and the same upload with our CLI based on minio-go (both using the same part sizes) result in different `ETag`s (the object size is identical). A subsequent upload with minio-go results in yet another `ETag`, meaning some randomness seems to be involved.

We looked at the code path leading to the individual parts being uploaded, and found the entry point to `uploadPart` to be here:

https://github.com/minio/minio-go/blob/master/api-put-object-streaming.go#L168-L170

The two empty strings are "md5Base64" and "sha256Hex" which can be passed to the S3 API for content integrity: the S3 API refuses the part if the uploaded content doesn't match with the hash supplied by the client. Without a hash, no validation happens.

Would there be a way for the client to compute each part's digest as part of the upload preparation, allowing to supply them to the S3 API?

**Comment by harshavardhana** [comment] 2019-06-20 08:31
@brutasse there is not guarantee that it should result in the same ETag if the server implementation has a bug.  ETag can also be different if the part size varies for each upload.

s3cmd has different purpose than minio-go, it has additional requirements to store additional metadata which needs to be precomputed which it does before uploading.

minio-go is a higher level library with abstractions and easy to use APIs, exposing lower level APIs is out of scope for minio-go

**Comment by harshavardhana** [comment] 2019-06-20 08:33
To validate the object is indeed uploaded wrong just do `mc cat | md5sum` and see if it matches.

**Comment by brutasse** [comment] 2019-06-20 08:34
> minio-go is a higher level library with abstractions and easy to use APIs, exposing lower level APIs is out of scope for minio-go

This is more about content integrity, which is easy to do at upload time, than low-level APIs.

> To validate the object is indeed uploaded wrong just do `mc cat | md5sum` and see if it matches.

With our use of minio-go, it never matches for objects larger than the multipart threshold.

**Comment by falzm** [comment] 2019-06-20 11:39
Hi @harshavardhana, we've tracked down the file content corruption issue (as @brutasse mentioned, even once re-downloaded the file checksum doesn't match) being linked to the use of a progress meter: I've disabled it from our current implementation and now the uploaded file checksum match when re-downloaded locally.

The problem might be located in the progress bar package we're using ([github.com/vbauerster/mpb](https://github.com/vbauerster/mpb/)/v4), but could you please check if there isn't something wrong with the [`minio.PutObjectOptions.Progress`](https://godoc.org/github.com/minio/minio-go#PutObjectOptions) implementation also?

Thank you

**Comment by vadmeste** [comment] 2019-06-20 12:05
@falzm it would be great if you could provide a sample code using the progress meter which reproduces this

**Comment by falzm** [comment] 2019-06-20 12:07
@vadmeste the code mentioned in the OP is actually a good simple example: https://github.com/exoscale/cli/blob/master/cmd/sos_upload.go

**Comment by harshavardhana** [comment] 2019-06-20 19:01
@falzm @brutasse can this be reproduced with `mc`?

```
~ mc cp bigfile myminio/testbucket/
bigfile:               1.00 GiB / 1.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 224.79 MiB/s 4s
```

```
~ mc cat myminio/testbucket/bigfile | md5sum
cd573cfaace07e7949bc0c46028904ff  -
```
```
~ md5sum bigfile
cd573cfaace07e7949bc0c46028904ff  bigfile
```

Even uploading to AWS S3 works 
```
~ mc cp bigfile s3/presto-datasets/
bigfile:               1.00 GiB / 1.00 GiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 34.69 MiB/s 29s
```

```
~ mc cat s3/presto-datasets/bigfile | md5sum
cd573cfaace07e7949bc0c46028904ff  -
```

So I don't think there is an issue in minio-go, FWIW I think the issue might be related to the exo command line and the usage of mpb (multi progress bar)

**Comment by harshavardhana** [comment] 2019-06-20 19:02
It would be quite useful if you can give us a self-contained Go program. I tried using exo command line against MinIO and failed to do so since it requires access to exo accounts which I have no interest registering at the moment. 

```toml
defaultaccount = "example"

[[accounts]]
  account = "example"
  sosEndpoint = "http://localhost:9000"
  key = "minio"
  secretkey = "minio123"
```

**Comment by vadmeste** [comment] 2019-06-20 20:26
@harshavardhana I was able to reproduce the issue with exoscale sos upload binary and it seems the following diff can fix the issue:

**Comment by harshavardhana** [comment] 2019-06-20 20:53
> It looks minio-go requires from progress to behave in a certain way but I believe this can be fixed with the way describe above

Can you elaborate this more? @vadmeste

**Comment by harshavardhana** [comment] 2019-06-20 21:02
> ```diff
> +       trashBuffer := make([]byte, len(b))
>         // Progress the hook with the total read bytes from the source.
> -       if _, herr := hr.hook.Read(b[:n]); herr != nil {
> +       if _, herr := hr.hook.Read(trashBuffer[:n]); herr != nil {
>                 if herr != io.EOF {
>                         return n, herr
>                 }
> ```

We shouldn't be allocating anything here if mpb doesn't modify the bytes in the reader it should work as is without making this allocation.  This means that every `b` allocated we will have to allocate another set of bytes to satisfy progress bar. That is not correct. 

It looks like there is a bug in mpb implementation of io.Reader

**Comment by harshavardhana** [comment] 2019-06-20 21:21
The correct fix is sent to exos/cli https://github.com/exoscale/cli/pull/157/files - closing this issue.

**Closed by harshavardhana** 2019-06-20 21:21 UTC
Labels: community, priority: medium

**Comment by falzm** [comment] 2019-06-21 07:17
Great, thank you for your help @harshavardhana!
