### ISSUE TITLE
TestPutObjectStream is not passing with latest and master minio

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-go#718] opened 2017-06-20 14:58 UTC
--- FAIL: TestPutObjectStreaming (0.00s)
        api_functional_v4_test.go:406: Test 1 Error: The request signature we calculated does not match the signature you provided. Check your key and signing method. minio-go-
testh1owqaacnr26h95qc test-object

**Comment by harshavardhana** [comment] 2017-06-20 18:49
Passes with `play.minio.io:9000` using this PR - https://github.com/minio/minio-go/pull/720

```
go test -v -run TestPutObjectStreaming
=== RUN   TestPutObjectStreaming
--- PASS: TestPutObjectStreaming (0.36s)
PASS
ok  	github.com/minio/minio-go	0.367s
```

**Comment by harshavardhana** [comment] 2017-06-21 01:27
This is because of 

```
commit 5db1e9f3dd74ecce06cbab1cf1c52930a62a302f
Author: Krishna Srinivas <krishna@minio.io>
Date:   Mon May 15 18:17:02 2017 -0700

    signature: use region from Auth header if server's region not configured (#4329)
```

**Comment by harshavardhana** [comment] 2017-06-21 02:28
Closing this as its not a bug in minio-go instead a regression on the server side and opening on the server.

**Closed by harshavardhana** 2017-06-21 02:28 UTC
Labels: priority: medium
