### ISSUE TITLE
Pull AWS credentials from environment

### ISSUE THREAD

**Issue by sidewinder12s** [minio/minio-go#520] opened 2016-09-24 07:43 UTC
Does the minio client support pulling the AWS credentials from environment variables or from the instance metadata service to support AWS instance roles?

**Comment by harshavardhana** [comment] 2016-09-24 09:05
> Does the minio client support pulling the AWS credentials from environment variables or from the instance metadata service to support AWS instance roles?

The easier way to do is simply do 

```
minio.New(os.Getenv("AWS_S3_ENDPOINT"), os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), true)
```

**Comment by sidewinder12s** [comment] 2016-09-27 18:42
@harshavardhana Would it make more sense to use the aws-sdk to use their credential providers which handle the different ways to get credentials or would that break with the simplicity of minio? Just wondering if it'd make more sense to implement that type of thing in minio or in the app using it: https://godoc.org/github.com/aws/aws-sdk-go/aws/credentials

**Comment by harshavardhana** [comment] 2016-09-27 19:57
> Would it make more sense to use the aws-sdk to use their credential providers which handle the different ways to get credentials or would that break with the simplicity of minio? Just wondering if it'd make more sense to implement that type of thing in minio or in the app using it: https://godoc.org/github.com/aws/aws-sdk-go/aws/credentials

We wanted to keep it simple @sidewinder12s - we don't have IAM like requirements so it would be better left for apps to do it.  An example of such an app is `https://github.com/minio/mc`

**Comment by harshavardhana** [comment] 2016-10-02 17:13
Closing with working as intended.

**Closed by harshavardhana** 2016-10-02 17:13 UTC
Labels: wontfix/invalid
