### ISSUE TITLE
The provided 'x-amz-content-sha256' header does not match what was computed

### ISSUE THREAD

**Issue by zhucan** [minio/minio-go#1234] opened 2020-02-27 14:29 UTC
**My test case:**
package main

import (
	"bytes"
	"fmt"

	"github.com/minio/minio-go"
)

func main() {
	// Use a secure connection.
	ssl := false

	// Initialize minio client object.
	minioClient, err := minio.NewWithRegion("10.0.12.240:8060", "LGDUL089742B3WAGG3DL", "FilsJxgSOu3qFZlEHj16AC1xrCdSZCGCYn7ghwiF", ssl, "us-east-1")

	if err != nil {
		fmt.Println(err)
		return
	}
	for i:=0; i<10;i++ {
		err := minioClient.MakeBucket(fmt.Sprintf("pvc-%d", i), "us-east-1")
		if err != nil {
			fmt.Println(err)
			continue
		}
		n, err := minioClient.PutObject("pvc-50932282-6de3-4f49-bcf3-095497fbb237", "csi-fs"+"/", bytes.NewReader([]byte("")), 0, minio.PutObjectOptions{})
		if err != nil {
			fmt.Println(err)
			continue
		}
		fmt.Println("Successfully uploaded bytes: ", n)
	}
}

Result:
![image](https://user-images.githubusercontent.com/13997135/75454587-9d83d400-59b0-11ea-80bb-66144a3e6a0e.png)

Sometimes, It's failed.

**Comment by vadmeste** [comment] 2020-02-27 15:34
@zhucan what S3 server is this ?

**Comment by harshavardhana** [comment] 2020-02-27 17:32
Closing as duplicate of #1235

**Closed by harshavardhana** 2020-02-27 17:32 UTC

**Comment by zhucan** [comment] 2020-02-28 03:19
> @zhucan what S3 server is this ?

ceph rgw.
